# Generated by Django 4.2.9 on 2024-11-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
    ]
