# Generated by Django 4.2.9 on 2024-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_alter_pedido_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='razon_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
