# Generated by Django 4.2.9 on 2024-11-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_pedido_razon_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('en progreso', 'En Progreso'), ('cancelado', 'Cancelado')], default='pendiente', max_length=11),
        ),
    ]
