# Generated by Django 4.2.9 on 2024-11-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_alter_pedido_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmacion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
