# Generated by Django 4.2.9 on 2024-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_pedido_confirmacion_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Empaqueta tu futuro con nuestras cajas multiusos...', max_length=500)),
            ],
        ),
    ]
