# Generated by Django 4.2.9 on 2024-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='titulo_dos',
            field=models.CharField(default='¡DESCUBRE LA CALIDAD QUE MARCA LA DIFERENCA!', max_length=500),
        ),
    ]
