# Generated by Django 4.2.9 on 2024-11-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0013_pagina_titulo_dos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='color_letra',
            field=models.CharField(default='#2b4e71', max_length=8),
        ),
    ]
