# Generated by Django 4.2.9 on 2024-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0014_pagina_color_letra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='color_letra',
        ),
        migrations.AddField(
            model_name='pagina',
            name='color_letra_titulo',
            field=models.CharField(default='#2b4e71', max_length=8),
        ),
        migrations.AddField(
            model_name='pagina',
            name='color_letra_titulo_dos',
            field=models.CharField(default='#fffffff', max_length=8),
        ),
    ]
