# Generated by Django 4.2.9 on 2024-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0017_pagina_color_boton_pagina_color_letra_boton'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='imagen_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/images/'),
        ),
    ]
