# Generated by Django 4.2.9 on 2024-11-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0018_pagina_imagen_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Empaqueta tu futuro con nuestras cajas multiusos...', max_length=500)),
                ('titulo_dos', models.CharField(default='¡DESCUBRE LA CALIDAD QUE MARCA LA DIFERENCA!', max_length=500)),
                ('color_letra_titulo', models.CharField(default='#2b4e71', max_length=8)),
                ('color_letra_titulo_dos', models.CharField(default='#ffffff', max_length=8)),
                ('txt_uno', models.TextField(default='')),
                ('txt_dos', models.TextField(default='')),
            ],
        ),
    ]
