# Generated by Django 4.2.9 on 2024-11-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0019_paginanosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginanosotros',
            name='color_txt_dos',
            field=models.CharField(default='#ffffff', max_length=8),
        ),
        migrations.AddField(
            model_name='paginanosotros',
            name='color_txt_uno',
            field=models.CharField(default='#2b4e71', max_length=8),
        ),
        migrations.AlterField(
            model_name='paginanosotros',
            name='titulo',
            field=models.CharField(default='¿Quiénes somos?', max_length=100),
        ),
        migrations.AlterField(
            model_name='paginanosotros',
            name='titulo_dos',
            field=models.CharField(default='Diferencias', max_length=500),
        ),
    ]
