# Generated by Django 4.2.9 on 2024-11-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0021_paginaproductos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_letra_titulo', models.CharField(default='#2b4e71', max_length=8)),
                ('color_letra_titulo_dos', models.CharField(default='#ffffff', max_length=8)),
                ('color_btn', models.CharField(default='#2b4e71', max_length=8)),
                ('color_letra_btn', models.CharField(default='#ffffff', max_length=8)),
            ],
        ),
    ]
